"""
Notification and Security Master tools.
"""
import csv
import os
import re
from datetime import datetime, timezone
from typing import List
from langchain_core.tools import tool
from ca_agent.config import SECURITY_MASTER_FILE


# ── Notification Tools ──────────────────────────────────────────────────────────

@tool
def draft_internal_notification(
    event_type: str | None,
    event_category: str | None,
    isin: str | None,
    issuer: str | None,
    record_date: str | None,
    ex_date: str | None,
    pay_date: str | None,
    election_deadline: str | None,
    gross_rate: str | None,
    currency: str | None,
    entitlements: List[dict],
    total_projected: str | None,
    urgency: str | None,
    narrative: str | None = ""
) -> str:
    """
    Draft a professional internal Corporate Actions notification.

    Formats a structured alert suitable for distribution to Portfolio
    Managers, Traders, and Operations teams. Includes all key event
    details, per-portfolio entitlements, and required actions.

    Returns:
        Formatted notification string.
    """
    event_type = event_type or ""
    event_category = event_category or "mandatory"
    isin = isin or ""
    issuer = issuer or "Unknown Issuer"
    record_date = record_date or ""
    ex_date = ex_date or ""
    pay_date = pay_date or ""
    election_deadline = election_deadline or ""
    gross_rate = gross_rate or "0"
    currency = currency or "USD"
    total_projected = total_projected or "0"
    urgency = urgency or "normal"
    narrative = narrative or ""

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    urgency_banner = {
        "critical": "🔴 CRITICAL — IMMEDIATE ACTION REQUIRED",
        "high":     "🟡 HIGH PRIORITY",
        "normal":   "🟢 FOR INFORMATION"
    }.get(urgency, "🟢 FOR INFORMATION")

    category_label = {
        "mandatory": "MANDATORY (No action required from PM)",
        "voluntary": "⚡ VOLUNTARY — PM ELECTION REQUIRED",
        "elective":  "⚡ ELECTIVE — PM ELECTION REQUIRED"
    }.get(event_category, event_category.upper())

    event_labels = {
        "DVCA": "Cash Dividend",
        "SPLF": "Stock Split",
        "MRGR": "Merger / Acquisition",
        "TEND": "Tender Offer",
        "RHTS": "Rights Issue",
        "BONU": "Bonus Issue"
    }
    event_label = event_labels.get(event_type, event_type)

    lines = [
        f"CORPORATE ACTIONS NOTIFICATION",
        f"Issued: {timestamp}",
        f"{'='*60}",
        f"{urgency_banner}",
        f"{'='*60}",
        f"",
        f"EVENT DETAILS",
        f"-" * 40,
        f"Event Type    : {event_label} ({event_type})",
        f"Category      : {category_label}",
        f"Issuer        : {issuer}",
        f"ISIN          : {isin}",
        f"Record Date   : {record_date}",
        f"Ex-Date       : {ex_date}",
        f"Pay/Settle    : {pay_date}",
    ]

    if election_deadline:
        lines.append(f"Election Deadline : ⚠️  {election_deadline} (UTC)")

    if gross_rate and gross_rate != "0":
        lines += [
            f"Rate          : {currency} {gross_rate} per share (gross)",
        ]

    lines += ["", "AFFECTED PORTFOLIOS & PROJECTED ENTITLEMENTS", "-" * 40]

    for ent in entitlements:
        if ent.get("type") == "shares":
            lines.append(
                f"  {ent['portfolio_name']:<25} {ent['quantity']:>10,} shares "
                f"→ {ent.get('new_shares', 'TBC'):>10,} new shares"
            )
        else:
            lines.append(
                f"  {ent['portfolio_name']:<25} {ent['quantity']:>10,} shares "
                f"→ {currency} {float(ent.get('gross_entitlement', 0)):>12,.2f} gross"
            )

    lines += [
        f"",
        f"  TOTAL PROJECTED: {currency} {float(total_projected):,.2f}",
        f"",
    ]

    if event_category in ("voluntary", "elective"):
        lines += [
            "REQUIRED ACTION",
            "-" * 40,
            "Portfolio Manager must confirm election decision before deadline.",
            "Please respond with: TENDER / DO NOT TENDER / PARTIAL (specify %)",
            "Contact Ops team immediately if unable to respond before deadline.",
            "",
        ]
    else:
        lines += [
            "ACTION",
            "-" * 40,
            "No election required. Entitlements will be processed automatically.",
            "Ops team will confirm upon receipt of custodian MT566 confirmation.",
            "",
        ]

    if narrative:
        lines += ["CUSTODIAN NARRATIVE", "-" * 40, narrative[:500], ""]

    lines += [
        "=" * 60,
        "This notification was generated by the CA Processing Agent.",
        "For queries, contact the Corporate Actions Operations team.",
    ]

    return "\n".join(lines)


@tool
def tag_recipients(event_category: str, urgency: str, asset_class: str = "Equity") -> list:
    """
    Determine the correct internal recipients for a CA notification.

    Args:
        event_category: "mandatory" | "voluntary" | "elective"
        urgency: "critical" | "high" | "normal"
        asset_class: "Equity" | "Fixed Income"

    Returns:
        List of recipient role strings.
    """
    recipients = ["operations_team", "ca_analyst"]

    if event_category in ("voluntary", "elective"):
        recipients.append("portfolio_manager")
        recipients.append("trader")

    if urgency == "critical":
        recipients.append("senior_management")
        recipients.append("compliance")

    if urgency in ("critical", "high"):
        recipients.append("risk_team")

    if asset_class == "Fixed Income":
        recipients.append("fixed_income_analyst")

    return list(set(recipients))  # deduplicate


# ── Security Master Tools ───────────────────────────────────────────────────────

@tool
def validate_security_identifiers(
    isin: str,
    cusip: str = "",
    sedol: str = ""
) -> dict:
    """
    Validate the format of ISIN, CUSIP, and SEDOL identifiers.

    Checks format rules only (not database lookup).
    ISIN: 12 chars, 2 alpha + 10 alphanumeric, Luhn checksum
    CUSIP: 9 chars alphanumeric
    SEDOL: 7 chars, first 6 alphanumeric + check digit

    Returns:
        Dict with validation results per identifier.
    """
    from ca_agent.tools.ingestion_tools import _isin_checksum_valid

    results = {}

    # ISIN
    isin_clean = isin.strip().upper()
    results["isin"] = {
        "value": isin_clean,
        "format_valid": bool(re.match(r'^[A-Z]{2}[A-Z0-9]{10}$', isin_clean)),
        "checksum_valid": _isin_checksum_valid(isin_clean),
        "issues": []
    }
    if not results["isin"]["format_valid"]:
        results["isin"]["issues"].append("ISIN must be 12 chars: 2 letters + 10 alphanumeric")
    if results["isin"]["format_valid"] and not results["isin"]["checksum_valid"]:
        results["isin"]["issues"].append("ISIN checksum digit invalid (ISO 6166)")

    # CUSIP
    if cusip:
        cusip_clean = cusip.strip().upper()
        results["cusip"] = {
            "value": cusip_clean,
            "format_valid": bool(re.match(r'^[A-Z0-9]{9}$', cusip_clean)),
            "issues": []
        }
        if not results["cusip"]["format_valid"]:
            results["cusip"]["issues"].append("CUSIP must be exactly 9 alphanumeric characters")
    else:
        results["cusip"] = {"value": "", "format_valid": None, "issues": ["Not provided"]}

    # SEDOL
    if sedol:
        sedol_clean = sedol.strip().upper()
        results["sedol"] = {
            "value": sedol_clean,
            "format_valid": bool(re.match(r'^[A-Z0-9]{6}\d$', sedol_clean)),
            "issues": []
        }
        if not results["sedol"]["format_valid"]:
            results["sedol"]["issues"].append("SEDOL must be 6 alphanumeric chars + 1 check digit")
    else:
        results["sedol"] = {"value": "", "format_valid": None, "issues": ["Not provided"]}

    all_valid = all(
        v.get("format_valid") is not False
        for v in results.values()
    )
    results["all_valid"] = all_valid

    return results


@tool
def check_security_master_record(isin: str) -> dict:
    """
    Look up a security in the Security Master file and identify
    any data quality issues.

    Checks for: missing mandatory fields, incorrect asset class,
    inactive securities, missing exchange codes.

    Args:
        isin: ISIN to look up.

    Returns:
        Dict with security record, issues list, and suggested fixes.
    """
    sm_file = SECURITY_MASTER_FILE
    if not os.path.exists(sm_file):
        return {
            "found": False,
            "issues": [f"Security master file not found: {sm_file}"],
            "suggested_fixes": ["Ensure SECURITY_MASTER_FILE env var is set correctly"]
        }

    with open(sm_file, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get("isin", "").strip().upper() == isin.upper():
                issues = []
                fixes = []

                mandatory_fields = {
                    "cusip": "CUSIP",
                    "sedol": "SEDOL",
                    "security_name": "Security Name",
                    "asset_class": "Asset Class",
                    "exchange": "Exchange",
                    "currency": "Currency",
                    "issuer_country": "Issuer Country"
                }

                for field, label in mandatory_fields.items():
                    if not row.get(field, "").strip():
                        issues.append(f"Missing mandatory field: {label}")
                        fixes.append(
                            f"Populate '{label}' field for {isin} in Security Master. "
                            f"Source from Bloomberg/Refinitiv or custodian confirmation."
                        )

                # Check active status
                if row.get("is_active", "").strip().lower() == "false":
                    issues.append("Security marked as INACTIVE in Security Master")
                    fixes.append(
                        "Verify if security should be reactivated. "
                        "Check if corporate action has changed the security status."
                    )

                return {
                    "found": True,
                    "record": dict(row),
                    "issues": issues,
                    "suggested_fixes": fixes,
                    "data_quality_score": f"{max(0, 100 - len(issues) * 15)}%"
                }

    return {
        "found": False,
        "record": {},
        "issues": [f"ISIN {isin} not found in Security Master"],
        "suggested_fixes": [
            f"Add new security record for {isin} to Security Master. "
            "Obtain all mandatory fields from custodian or data vendor before adding."
        ]
    }
